import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { type Locale, routing } from '@/i18n/routing';
import { setRequestLocale } from 'next-intl/server';
import BaseLayout from '@/components/layouts/BaseLayout';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default async function LocaleLayout({
  children,
  params: { locale }
}: Readonly<{
  children: React.ReactNode;
  params: { locale: Locale };
}>) {
  // Ensure that the incoming `locale` is valid
  if (!routing.locales.includes(locale as Locale)) {
    notFound();
  }

  // Enable static rendering
  setRequestLocale(locale);

  return <BaseLayout locale={locale}>{children}</BaseLayout>;
}

export function generateStaticParams({
  params: { locale }
}: {
  params: { locale: Locale };
}) {
  return routing.locales.map(locale => ({ locale }));
}
